version: '3.8'

services:
  otp-auth-service:
    build: .
    container_name: otp-service
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./credentials:/app/credentials:ro
    restart: unless-stopped